const Hotel = require('./Hotel')
const Habitaciones = require('./Habitacion')
const Booking = require('./Booking')
Hotel.hasMany(Habitaciones)
Habitaciones.belongsTo(Hotel)
Booking.belongsTo(Habitaciones)
Habitaciones.hasOne(Booking)
Booking.belongsTo(Hotel)
Hotel.hasMany(Booking)
